version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the production Docker image...
      - docker build -t cyberlkhome/react-jwt-auth .
      - docker build -t cyberlkhome/node-js-jwt-auth .
      - docker tag cyberlkhome/react-jwt-auth cyberlkhome/react-jwt-auth
      - docker tag cyberlkhome/node-js-jwt-auth cyberlkhome/node-js-jwt-auth
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push cyberlkhome/react-jwt-auth
      - docker push cyberlkhome/node-js-jwt-auth
