# Specify a base image
FROM node:14.18.2-alpine AS alpine

WORKDIR /node-js-jwt-auth

# Install dependencies
COPY package.json .
RUN npm install 
COPY . .

# Default command
CMD ["npm", "run", "test"]